from enum import StrEnum

class Category(StrEnum):
    HOUSING = "HOUSING"
    FOOD = "FOOD"
    TRANSPORT = "TRANSPORT"
    ENTERTAINMENT = "ENTERTAINMENT"
    HEALTH = "HEALTH"
    EDUCATION = "EDUCATION"
    CLOTHING = "CLOTHING"
    SALARY = "SALARY"
    FREELANCE = "FREELANCE"
    INVESTMENT = "INVESTMENT"
    OTHER = "OTHER"

    